language: node_js
node_js:
  - "12.13.1"
cache:
  directories:
  - node_modules
notifications:
  email:
    recipients:
      - chungtran4078@gmail.com
    on_success: always
    on_failure: always
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  on:
    branch: develop